package employeedatabase;

import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Patricia
 */
public class AddEmployeePartTimeFrame extends javax.swing.JFrame {

    private static EmployeeInfo employee;
    private int sex = -1;
    private int employeeNumber;
    private String fName;
    private String lName;
    private int workLoc = -1;
    private double dRate;
    private double hrWage;
    private double hrWeek;
    private double wkYear;

    /**
     * Creates new form AddEmployeeFrame
     */
    public AddEmployeePartTimeFrame() {
        initComponents();
    }

    public static EmployeeInfo returnEmployee() {
        return employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empSexButtons = new javax.swing.ButtonGroup();
        pEmpPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        empNum = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        workLocation = new javax.swing.JComboBox<>();
        deducRate = new javax.swing.JTextField();
        hrlyWage = new javax.swing.JTextField();
        hrsWeek = new javax.swing.JTextField();
        weekYr = new javax.swing.JTextField();
        percentSymbol = new javax.swing.JLabel();
        dollarSign = new javax.swing.JLabel();
        button_complete = new javax.swing.JButton();
        button_return = new javax.swing.JButton();
        empNumError = new javax.swing.JLabel();
        dRateError = new javax.swing.JLabel();
        hWageError = new javax.swing.JLabel();
        hWeekError = new javax.swing.JLabel();
        wYearError = new javax.swing.JLabel();
        fNameError = new javax.swing.JLabel();
        lNameError = new javax.swing.JLabel();
        sexError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        pEmpPanel.setBackground(java.awt.Color.lightGray);

        titleLabel.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 102, 102));
        titleLabel.setText("ADD PART TIME EMPLOYEE");

        empNum.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        empNum.setForeground(java.awt.Color.lightGray);
        empNum.setText("Employee Number");
        empNum.setFocusable(false);
        empNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedEmpNum(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostEmpNum(evt);
            }
        });
        empNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        firstName.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        firstName.setForeground(java.awt.Color.lightGray);
        firstName.setText("First Name");
        firstName.setFocusable(false);
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedFirstName(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostFirstName(evt);
            }
        });
        firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        lastName.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        lastName.setForeground(java.awt.Color.lightGray);
        lastName.setText("Last Name");
        lastName.setFocusable(false);
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedLastName(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostLastName(evt);
            }
        });
        lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        empSexButtons.add(male);
        male.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        male.setForeground(java.awt.Color.darkGray);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        empSexButtons.add(female);
        female.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        female.setForeground(java.awt.Color.darkGray);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        empSexButtons.add(other);
        other.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        other.setForeground(java.awt.Color.darkGray);
        other.setText("Other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        workLocation.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        workLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Work Location (select one)", "Mississauga", "Toronto", "Ottawa" }));
        workLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostWorkLocation(evt);
            }
        });

        deducRate.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        deducRate.setForeground(java.awt.Color.lightGray);
        deducRate.setText("Deductions Rate");
        deducRate.setFocusable(false);
        deducRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedDeducRate(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostDeducRate(evt);
            }
        });
        deducRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        hrlyWage.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        hrlyWage.setForeground(java.awt.Color.lightGray);
        hrlyWage.setText("Hourly Wage");
        hrlyWage.setFocusable(false);
        hrlyWage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedHourlyWage(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fosucLostHourlyWage(evt);
            }
        });
        hrlyWage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        hrsWeek.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        hrsWeek.setForeground(java.awt.Color.lightGray);
        hrsWeek.setText("Hours Per Week");
        hrsWeek.setFocusable(false);
        hrsWeek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedHoursPerWeek(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostHoursPerWeek(evt);
            }
        });
        hrsWeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        weekYr.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        weekYr.setForeground(java.awt.Color.lightGray);
        weekYr.setText("Weeks Per Year");
        weekYr.setFocusable(false);
        weekYr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedWeeksPerYear(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostWeeksPerYear(evt);
            }
        });
        weekYr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeFocusable(evt);
            }
        });

        percentSymbol.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        percentSymbol.setForeground(java.awt.Color.darkGray);
        percentSymbol.setText("%");

        dollarSign.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        dollarSign.setForeground(java.awt.Color.darkGray);
        dollarSign.setText("$");

        button_complete.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_complete.setForeground(new java.awt.Color(255, 255, 255));
        button_complete.setText("COMPLETE");
        button_complete.setBorderPainted(false);
        button_complete.setContentAreaFilled(false);
        button_complete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_complete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_complete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_completeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_completeMouseEntered(evt);
            }
        });
        button_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_completeActionPerformed(evt);
            }
        });

        button_return.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_return.setForeground(new java.awt.Color(255, 255, 255));
        button_return.setText("RETURN");
        button_return.setBorderPainted(false);
        button_return.setContentAreaFilled(false);
        button_return.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_return.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_returnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_returnMouseEntered(evt);
            }
        });
        button_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_returnActionPerformed(evt);
            }
        });

        empNumError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        empNumError.setForeground(java.awt.Color.lightGray);
        empNumError.setText("invalid input");

        dRateError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        dRateError.setForeground(java.awt.Color.lightGray);
        dRateError.setText("invalid input");

        hWageError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        hWageError.setForeground(java.awt.Color.lightGray);
        hWageError.setText("invalid input");

        hWeekError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        hWeekError.setForeground(java.awt.Color.lightGray);
        hWeekError.setText("invalid input");

        wYearError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        wYearError.setForeground(java.awt.Color.lightGray);
        wYearError.setText("invalid input");

        fNameError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        fNameError.setForeground(java.awt.Color.lightGray);
        fNameError.setText("please input a name");

        lNameError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        lNameError.setForeground(java.awt.Color.lightGray);
        lNameError.setText("please input a name");

        sexError.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        sexError.setForeground(java.awt.Color.lightGray);
        sexError.setText("please select one:");

        javax.swing.GroupLayout pEmpPanelLayout = new javax.swing.GroupLayout(pEmpPanel);
        pEmpPanel.setLayout(pEmpPanelLayout);
        pEmpPanelLayout.setHorizontalGroup(
            pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                        .addComponent(dollarSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEmpPanelLayout.createSequentialGroup()
                                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pEmpPanelLayout.createSequentialGroup()
                                                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(deducRate)
                                                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                                                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(lastName, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(empNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                                                            .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(hrlyWage)
                                                                .addComponent(hrsWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(weekYr, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(pEmpPanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(empNumError)
                                                                    .addComponent(hWageError)
                                                                    .addComponent(hWeekError))))
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(pEmpPanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lNameError)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(percentSymbol))
                                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wYearError)
                                            .addComponent(dRateError))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                            .addGroup(pEmpPanelLayout.createSequentialGroup()
                                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(fNameError))
                                    .addComponent(button_return))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(workLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(male)
                                .addComponent(female)
                                .addComponent(other)
                                .addComponent(button_complete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pEmpPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(sexError)))
                        .addGap(11, 11, 11))))
        );
        pEmpPanelLayout.setVerticalGroup(
            pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEmpPanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empNumError)
                    .addComponent(sexError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deducRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentSymbol))
                        .addGap(4, 4, 4)
                        .addComponent(dRateError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dollarSign))
                        .addGap(1, 1, 1)
                        .addComponent(hWageError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hrsWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(other)
                        .addGap(18, 18, 18)
                        .addComponent(workLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(hWeekError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_complete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(pEmpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wYearError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_return)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //changes text colour of buttons to dark gray upon mouse enterance
    private void button_completeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_completeMouseEntered
        button_complete.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_completeMouseEntered

    private void button_returnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnMouseEntered
        button_return.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_returnMouseEntered
    
    //changes text colour of buttons to white upon mouse exit
    private void button_completeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_completeMouseExited
        button_complete.setForeground(Color.white);
    }//GEN-LAST:event_button_completeMouseExited

    private void button_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnMouseExited
        button_return.setForeground(Color.white);
    }//GEN-LAST:event_button_returnMouseExited

    //sets an action for when each button is clicked
    private void button_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_completeActionPerformed
        int error = 0;  //variable that will chnage in value if an error is detected
        
        MyHashTable hashTable = EmployeeDatabase.returnHashTable();
        int search = hashTable.searchEmployee(employeeNumber);

        //checks for any errors in input before instatiating a new employee:
        if (firstName.getText().equals("First Name")) {
            fNameError.setForeground(Color.red);
            error = 1;
        }
        
        if (lastName.getText().equals("Last Name")) {
            lNameError.setForeground(Color.red);
            error = 1;
        }
        
        if (employeeNumber<0){
            empNumError.setForeground(Color.red);
            error=1;
        }
        
        if (search != -1) {
            empNumError.setForeground(Color.red);
            error=1;
        }
        
        if (empNum.getText().equals("Employee Number")) {
            empNumError.setForeground(Color.red);
            error = 1;
        }
        if (deducRate.getText().equals("Deductions Rate")) {
            dRateError.setForeground(Color.red);
            error = 1;
        }
        if (hrlyWage.getText().equals("Hourly Wage")) {
            hWageError.setForeground(Color.red);
            error = 1;
        }
        if (hrsWeek.getText().equals("Hours Per Week")) {
            hWeekError.setForeground(Color.red);
            error = 1;
        }
        if (weekYr.getText().equals("Weeks Per Year")) {
            wYearError.setForeground(Color.red);
            error = 1;
        }
        if (workLoc == -1) {
            workLocation.setForeground(Color.red);
            error = 1;
        }
        if (sex == -1) {
            sexError.setForeground(Color.red);
            error = 1;
        }

        //if no errors, instantiates a new employee and places it into the hash table:
        if (error != 1) {

            fName = firstName.getText();
            lName = lastName.getText();

            try {
                employee = new PartTimeEmployee(employeeNumber, fName, lName, sex, workLoc, dRate, hrWage, hrWeek, wkYear);

                hashTable.addEmployee(employee);

                dispose();
                new MainMenu().setVisible(true);            //opens main menu window
                new AddSuccessfulFrame().setVisible(true);  //opens "add successful" popup

            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_button_completeActionPerformed

    private void button_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_returnActionPerformed
        dispose();
        new MainMenu().setVisible(true);                    //opens main menu window
    }//GEN-LAST:event_button_returnActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        sexError.setForeground(Color.lightGray);
        sex = 0;
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        sexError.setForeground(Color.lightGray);
        sex = 1;
    }//GEN-LAST:event_femaleActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        sexError.setForeground(Color.lightGray);
        sex = 2;
    }//GEN-LAST:event_otherActionPerformed

    //sets action to be performed upon gain of focus
    private void focusGainedEmpNum(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedEmpNum
        empNumError.setForeground(Color.lightGray);
        if (empNum.getText().equals("Employee Number")) {
            empNum.setText("");
            empNum.setForeground(Color.darkGray);
            empNum.setFont(empNum.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedEmpNum
    
    private void focusGainedFirstName(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedFirstName
        fNameError.setForeground(Color.lightGray);
        if (firstName.getText().equals("First Name")) {
            firstName.setText("");
            firstName.setForeground(Color.darkGray);
            firstName.setFont(firstName.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedFirstName

    private void focusGainedLastName(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedLastName
        lNameError.setForeground(Color.lightGray);
        if (lastName.getText().equals("Last Name")) {
            lastName.setText("");
            lastName.setForeground(Color.darkGray);
            lastName.setFont(lastName.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedLastName

    private void focusGainedDeducRate(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedDeducRate
        dRateError.setForeground(Color.lightGray);
        if (deducRate.getText().equals("Deductions Rate")) {
            deducRate.setText("");
            deducRate.setForeground(Color.darkGray);
            deducRate.setFont(deducRate.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedDeducRate

    private void focusGainedHourlyWage(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedHourlyWage
        hWageError.setForeground(Color.lightGray);
        if (hrlyWage.getText().equals("Hourly Wage")) {
            hrlyWage.setText("");
            hrlyWage.setForeground(Color.darkGray);
            hrlyWage.setFont(hrlyWage.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedHourlyWage

    private void focusGainedHoursPerWeek(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedHoursPerWeek
        hWeekError.setForeground(Color.lightGray);
        if (hrsWeek.getText().equals("Hours Per Week")) {
            hrsWeek.setText("");
            hrsWeek.setForeground(Color.darkGray);
            hrsWeek.setFont(hrsWeek.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedHoursPerWeek

    private void focusGainedWeeksPerYear(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedWeeksPerYear
        wYearError.setForeground(Color.lightGray);
        if (weekYr.getText().equals("Weeks Per Year")) {
            weekYr.setText("");
            weekYr.setForeground(Color.darkGray);
            weekYr.setFont(weekYr.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_focusGainedWeeksPerYear

    //sets an action to be performed upon loss of focus: if error detected, a message will be displayed
    private void focusLostEmpNum(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostEmpNum
        if (empNum.getText().equals("")) {
            empNum.setText("Employee Number");
            empNum.setForeground(Color.lightGray);
            empNum.setFont(empNum.getFont().deriveFont(Font.ITALIC));
        }
        try {
            employeeNumber = Integer.parseInt(empNum.getText());
        } catch (Exception e) {
            empNumError.setForeground(Color.red);
        }
        
        MyHashTable hashTable = EmployeeDatabase.returnHashTable();
        
        if (hashTable.searchEmployee(employeeNumber) != -1){
            empNumError.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostEmpNum

    private void focusLostFirstName(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostFirstName
        if (firstName.getText().equals("")) {
            firstName.setText("First Name");
            firstName.setForeground(Color.lightGray);
            firstName.setFont(firstName.getFont().deriveFont(Font.ITALIC));
        }
        if (firstName.getText().equals("First Name")) {
            fNameError.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostFirstName

    private void focusLostLastName(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostLastName
        if (lastName.getText().equals("")) {
            lastName.setText("Last Name");
            lastName.setForeground(Color.lightGray);
            lastName.setFont(lastName.getFont().deriveFont(Font.ITALIC));
        }
        if (lastName.getText().equals("Last Name")) {
            lNameError.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostLastName

    private void focusLostDeducRate(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostDeducRate
        if (deducRate.getText().equals("")) {
            deducRate.setText("Deductions Rate");
            deducRate.setForeground(Color.lightGray);
            deducRate.setFont(deducRate.getFont().deriveFont(Font.ITALIC));
        }
        try {
            dRate = Double.parseDouble(deducRate.getText()) / 100;
        } catch (Exception e) {
            dRateError.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostDeducRate

    private void fosucLostHourlyWage(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fosucLostHourlyWage
        if (hrlyWage.getText().equals("")) {
            hrlyWage.setText("Hourly Wage");
            hrlyWage.setForeground(Color.lightGray);
            hrlyWage.setFont(hrlyWage.getFont().deriveFont(Font.ITALIC));
        }
        try {
            hrWage = Double.parseDouble(hrlyWage.getText());
        } catch (Exception e) {
            hWageError.setForeground(Color.red);
        }

        if (hrWage <= 0) {
            hWageError.setForeground(Color.red);
        }
    }//GEN-LAST:event_fosucLostHourlyWage

    private void focusLostHoursPerWeek(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostHoursPerWeek
        if (hrsWeek.getText().equals("")) {
            hrsWeek.setText("Hours Per Week");
            hrsWeek.setForeground(Color.lightGray);
            hrsWeek.setFont(hrsWeek.getFont().deriveFont(Font.ITALIC));
        }

        try {
            hrWeek = Double.parseDouble(hrsWeek.getText());
        } catch (Exception e) {
            hWeekError.setForeground(Color.red);
        }

        if (hrWeek <= 0) {
            hWeekError.setForeground(Color.red);
        } else if (hrWeek > 168) {
            hWeekError.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostHoursPerWeek

    private void focusLostWeeksPerYear(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostWeeksPerYear
        if (weekYr.getText().equals("")) {
            weekYr.setText("Weeks Per Year");
            weekYr.setForeground(Color.lightGray);
            weekYr.setFont(weekYr.getFont().deriveFont(Font.ITALIC));
        }
        try {
            wkYear = Double.parseDouble(weekYr.getText());
        } catch (Exception e) {
            wYearError.setForeground(Color.red);
        }

        if (wkYear <= 0) {
            wYearError.setForeground(Color.red);
        } else if (wkYear > 52) {
            wYearError.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostWeeksPerYear

    private void makeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeFocusable
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_makeFocusable

    private void focusLostWorkLocation(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostWorkLocation
        if (workLocation.getSelectedItem() == "Toronto") {
            workLoc = 0;
        } else if (workLocation.getSelectedItem() == "Mississauga") {
            workLoc = 1;
        } else if (workLocation.getSelectedItem() == "Ottawa") {
            workLoc = 2;
        } else {
            workLoc = -1;
        }

        if (workLoc == -1) {
            workLocation.setForeground(Color.red);
        }
    }//GEN-LAST:event_focusLostWorkLocation

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeePartTimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeePartTimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeePartTimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeePartTimeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeePartTimeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_complete;
    private javax.swing.JButton button_return;
    private javax.swing.JLabel dRateError;
    private javax.swing.JTextField deducRate;
    private javax.swing.JLabel dollarSign;
    private javax.swing.JTextField empNum;
    private javax.swing.JLabel empNumError;
    private javax.swing.ButtonGroup empSexButtons;
    private javax.swing.JLabel fNameError;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel hWageError;
    private javax.swing.JLabel hWeekError;
    private javax.swing.JTextField hrlyWage;
    private javax.swing.JTextField hrsWeek;
    private javax.swing.JLabel lNameError;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton other;
    private javax.swing.JPanel pEmpPanel;
    private javax.swing.JLabel percentSymbol;
    private javax.swing.JLabel sexError;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wYearError;
    private javax.swing.JTextField weekYr;
    private javax.swing.JComboBox<String> workLocation;
    // End of variables declaration//GEN-END:variables
}
