/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import static employeedatabase.MyHashTable.buckets;
import java.awt.Color;

/**
 *
 * @author Patricia
 */
public class CheckRemoveFrame extends javax.swing.JFrame {
    private String sex;
    private String workLoc;
    /**
     * Creates new form CheckRemoveFrame
     */
    public CheckRemoveFrame() {
        initComponents();
        
        //check if an existing employee number was selected in previous frame
        if (RemoveEmployeeFrame.empToRemove() == -1) {
            empInfo.setForeground(Color.red);
            empInfo.append("this employee does not exist");
        } else {

            //displays employee to allow user to confirm this is they employee they want to delete
            empInfo.append("\n Employee Number: " + RemoveEmployeeFrame.empToRemove());
            MyHashTable hashTable = EmployeeDatabase.returnHashTable();

            int bucketNum = hashTable.calcBucket(RemoveEmployeeFrame.empToRemove());

            for (int x = 0; x < buckets[bucketNum].size(); x++) {

                EmployeeInfo employee = buckets[bucketNum].get(x);

                if (employee.getSex() == 0) {
                    sex = "male";
                } else if (employee.getSex() == 1) {
                    sex = "female";
                } else if (employee.getSex() == 2) {
                    sex = "other";
                }

                if (employee.getWorkLocation() == 0) {
                    workLoc = "Toronto";
                } else if (employee.getWorkLocation() == 1) {
                    workLoc = "Mississauga";
                } else if (employee.getWorkLocation() == 2) {
                    workLoc = "Ottawa";
                }

                if (employee.getEmpNumber() == RemoveEmployeeFrame.empToRemove()) {
                    empInfo.append("\n First Name: " + employee.getFirstName());
                    empInfo.append("\n Last Name: " + employee.getLastName());
                    empInfo.append("\n Sex: " + sex);
                    empInfo.append("\n Work Location: " + workLoc);
                    empInfo.append("\n Deductions Rate: " + employee.getDedustionsRate() * 100 + "%");

                    if (employee.empType().equals("p")) {
                        double hrWage = employee.getHourlyWage();
                        double hrWeek = employee.getHoursPerWeek();
                        double wkYear = employee.getWeeksPerYear();
                        empInfo.append("\nHourly Wage: " + hrWage);
                        empInfo.append("\nHours Per Week :" + hrWeek);
                        empInfo.append("\nWeeks Per Year: " + wkYear);
                    } else if (employee.empType().equals("f")) {
                        double salary = employee.getAnnualIncome();
                        empInfo.append("\nAnnual Income: " + salary);
                    }

                    empInfo.append("\n Annual Income: " + employee.calcAnnualIncome());
                }
            }
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        empInfo = new javax.swing.JTextArea();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        title.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        title.setForeground(java.awt.Color.darkGray);
        title.setText("Are You Sure You Want To Remove?");

        empInfo.setEditable(false);
        empInfo.setBackground(new java.awt.Color(204, 204, 204));
        empInfo.setColumns(20);
        empInfo.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        empInfo.setForeground(java.awt.Color.darkGray);
        empInfo.setRows(5);

        yesButton.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        yesButton.setForeground(new java.awt.Color(255, 255, 255));
        yesButton.setText("YES");
        yesButton.setBorderPainted(false);
        yesButton.setContentAreaFilled(false);
        yesButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yesButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        yesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yesButtonbackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yesButtonbackMouseEntered(evt);
            }
        });
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        noButton.setForeground(new java.awt.Color(255, 255, 255));
        noButton.setText("NO");
        noButton.setBorderPainted(false);
        noButton.setContentAreaFilled(false);
        noButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        noButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noButtonbackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noButtonbackMouseEntered(evt);
            }
        });
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yesButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(empInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(empInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //changes text colour of button to white upon mouse enterance
    private void yesButtonbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesButtonbackMouseExited
        yesButton.setForeground(Color.white);
    }//GEN-LAST:event_yesButtonbackMouseExited

    private void noButtonbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noButtonbackMouseExited
        noButton.setForeground(Color.white);
    }//GEN-LAST:event_noButtonbackMouseExited

    //changes text colour of button to dark gray upon mouse entered
    private void yesButtonbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesButtonbackMouseEntered
        yesButton.setForeground(Color.darkGray);
    }//GEN-LAST:event_yesButtonbackMouseEntered

    private void noButtonbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noButtonbackMouseEntered
        noButton.setForeground(Color.darkGray);
    }//GEN-LAST:event_noButtonbackMouseEntered

    //sets an action upon button click
    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        dispose();
        //opens removing frame
        new RemovingFrame().setVisible(true);
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_noButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckRemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckRemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckRemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckRemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckRemoveFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea empInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel title;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
