package employeedatabase;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Patricia
 */
public class DisplayEmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form DisplayEmployeeFrame
     */
    //private static EmployeeInfo employee;
    private String sex;
    private int employeeNumber;
    private String fName;
    private String lName;
    private String workLoc;
    private double dRate;
    private double yrIncome;

    public DisplayEmployeeFrame() {
        initComponents();
        if (MyHashTable.numOfEmp() == 0){
            empDisplay.setForeground(Color.red);
            empDisplay.append("No employees to display.");
        }
        else{
            display();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayEmpPane = new javax.swing.JScrollPane();
        empDisplay = new javax.swing.JTextArea();
        title = new javax.swing.JLabel();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        displayEmpPane.setBackground(new java.awt.Color(102, 102, 102));
        displayEmpPane.setOpaque(false);

        empDisplay.setEditable(false);
        empDisplay.setBackground(new java.awt.Color(225, 225, 225));
        empDisplay.setColumns(20);
        empDisplay.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        empDisplay.setRows(5);
        empDisplay.setSelectionColor(new java.awt.Color(51, 51, 51));
        displayEmpPane.setViewportView(empDisplay);

        title.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        title.setForeground(java.awt.Color.darkGray);
        title.setText("EMPLOYEE DATABASE");

        button_back.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_back.setForeground(new java.awt.Color(255, 255, 255));
        button_back.setText("BACK TO MENU");
        button_back.setBorderPainted(false);
        button_back.setContentAreaFilled(false);
        button_back.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_back.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_back)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(displayEmpPane, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayEmpPane, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        button_back.setForeground(Color.white);
    }//GEN-LAST:event_backMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        button_back.setForeground(Color.darkGray);
    }//GEN-LAST:event_backMouseEntered

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_button_backActionPerformed

    private void display() {

        for (int x = 0; x < MyHashTable.numOfBuckets(); x++) {

            for (int y = 0; y < MyHashTable.buckets[x].size(); y++) {
                
                EmployeeInfo employee = MyHashTable.buckets[x].get(y);

                if (employee.getSex() == 0) {
                    sex = "male";
                } else if (employee.getSex() == 1) {
                    sex = "female";
                } else if (employee.getSex() == 2) {
                    sex = "other";
                }

                if (employee.getWorkLocation() == 0) {
                    workLoc = "Toronto";
                } else if (employee.getWorkLocation() == 1) {
                    workLoc = "Mississauga";
                } else if (employee.getWorkLocation() == 2) {
                    workLoc = "Ottawa";
                }
                
                fName = employee.getFirstName();
                lName = employee.getLastName();
                employeeNumber = employee.getEmpNumber();
                yrIncome = employee.calcAnnualIncome();
                dRate = employee.getDedustionsRate()*100;
                
                empDisplay.append("First Name: " + fName);
                empDisplay.append("\nLast Name: " + lName);
                empDisplay.append("\nEmployee Number: " + employeeNumber);
                empDisplay.append("\nSex: " + sex);
                empDisplay.append("\nWork Location: " + workLoc);
                empDisplay.append("\nDeductions Rate: " + dRate + "%");
                if (employee.empType().equals("p")){
                    double hrWage = employee.getHourlyWage();
                    double hrWeek = employee.getHoursPerWeek();
                    double wkYear = employee.getWeeksPerYear();
                    empDisplay.append("\nHourly Wage: " + hrWage);
                    empDisplay.append("\nHours Per Week: " +hrWeek);
                    empDisplay.append("\nWeeks Per Year: " + wkYear);
                }
                else if (employee.empType().equals("f")){
                    double salary = employee.getAnnualIncome();
                    empDisplay.append("\nYearly Salary: " + salary);
                }
                
                empDisplay.append("\nAnnual Income: $" + yrIncome);
                empDisplay.append("\n ");
                empDisplay.append("\n ");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back;
    private javax.swing.JScrollPane displayEmpPane;
    private javax.swing.JTextArea empDisplay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
