/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import java.awt.Color;
import java.awt.Font;
import static employeedatabase.MyHashTable.buckets;

/**
 *
 * @author Megan
 */
public class EditPartTimeEmployee extends javax.swing.JFrame {

    private static EmployeeInfo employee;
    MyHashTable hashTable = EmployeeDatabase.returnHashTable();
    private int sex;
    private int employeeNumber;
    private String fName;
    private String lName;
    private int workLoc;
    private double dRate;
    private double hrWage;
    private double hrWeek;
    private double wkYear;
    private int originalEmpNum;

    /**
     * Creates new form EditPartTimeEmployee
     */
    public EditPartTimeEmployee() {
        int bucketNum = hashTable.calcBucket(EditEmployeeSearchFrame.getEmpNum());
            for (int x = 0; x < EditEmployeeSearchFrame.returnSearch(); x++) {

            employee = hashTable.buckets[bucketNum].get(x);
        }
        originalEmpNum = employee.getEmpNumber();
        sex = employee.getSex();
        workLoc = employee.getWorkLocation();
        employeeNumber = employee.getEmpNumber();
        fName = employee.getFirstName();
        lName = employee.getLastName();
        dRate = (employee.getDedustionsRate())*100;
        hrWage = employee.getHourlyWage();
        hrWeek = employee.getHoursPerWeek();
        wkYear = employee.getWeeksPerYear();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        empNum = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        workLocation = new javax.swing.JComboBox<>();
        deducRate = new javax.swing.JTextField();
        hrlyWage = new javax.swing.JTextField();
        hrsWeek = new javax.swing.JTextField();
        weekYr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        button_complete = new javax.swing.JButton();
        button_return = new javax.swing.JButton();
        empNumError = new javax.swing.JLabel();
        dRateError = new javax.swing.JLabel();
        hWageError = new javax.swing.JLabel();
        hWeekError = new javax.swing.JLabel();
        wYearError = new javax.swing.JLabel();
        fNameError = new javax.swing.JLabel();
        lNameError = new javax.swing.JLabel();
        sexError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);

        jLabel7.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("EDIT PART TIME EMPLOYEE");

        empNum.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        empNum.setForeground(java.awt.Color.darkGray);
        empNum.setText(getEmpNum());
        empNum.setToolTipText("");
        empNum.setFocusable(false);
        empNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empNumfocusG1(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empNumfocusL1(evt);
            }
        });
        empNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empNummakeFocusable(evt);
            }
        });

        firstName.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        firstName.setForeground(java.awt.Color.darkGray);
        firstName.setText(getFirstName());
        firstName.setFocusable(false);
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNamefocusG2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNamefocusL2(evt);
            }
        });
        firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                firstNamemakeFocusable(evt);
            }
        });

        lastName.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        lastName.setForeground(java.awt.Color.darkGray);
        lastName.setText(getLastName());
        lastName.setFocusable(false);
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNamefocusG3(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNamefocusL3(evt);
            }
        });
        lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lastNamemakeFocusable(evt);
            }
        });

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        male.setForeground(java.awt.Color.darkGray);
        male.setSelected(getSexMale());
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        female.setForeground(java.awt.Color.darkGray);
        female.setSelected(getSexFemale());
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(other);
        other.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        other.setForeground(java.awt.Color.darkGray);
        other.setSelected(getSexOther());
        other.setText("Other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        workLocation.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        workLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Work Location (select one)", "Mississauga", "Toronto", "Ottawa" }));
        workLocation.setSelectedIndex(getWorkLoc());

        deducRate.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        deducRate.setForeground(java.awt.Color.darkGray);
        deducRate.setText(getDRate());
        deducRate.setFocusable(false);
        deducRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deducRatefocusG4(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deducRatefocusL4(evt);
            }
        });
        deducRate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deducRatemakeFocusable(evt);
            }
        });

        hrlyWage.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        hrlyWage.setForeground(java.awt.Color.darkGray);
        hrlyWage.setText(getHrWage());
        hrlyWage.setFocusable(false);
        hrlyWage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hrlyWagefocusG5(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hrlyWagefosucL5(evt);
            }
        });
        hrlyWage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hrlyWagemakeFocusable(evt);
            }
        });

        hrsWeek.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        hrsWeek.setForeground(java.awt.Color.darkGray);
        hrsWeek.setText(getHrWeek());
        hrsWeek.setFocusable(false);
        hrsWeek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hrsWeekfocusG6(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hrsWeekfocusL6(evt);
            }
        });
        hrsWeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hrsWeekmakeFocusable(evt);
            }
        });

        weekYr.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        weekYr.setForeground(java.awt.Color.darkGray);
        weekYr.setText(getWkYear());
        weekYr.setFocusable(false);
        weekYr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weekYrfocusG7(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                weekYrfocusL7(evt);
            }
        });
        weekYr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                weekYrmakeFocusable(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel8.setForeground(java.awt.Color.darkGray);
        jLabel8.setText("%");

        jLabel9.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel9.setForeground(java.awt.Color.darkGray);
        jLabel9.setText("$");

        button_complete.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_complete.setForeground(new java.awt.Color(255, 255, 255));
        button_complete.setText("COMPLETE");
        button_complete.setBorderPainted(false);
        button_complete.setContentAreaFilled(false);
        button_complete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_complete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_complete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_completecompleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_completecompleteMouseExited(evt);
            }
        });
        button_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_completeActionPerformed(evt);
            }
        });

        button_return.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_return.setForeground(new java.awt.Color(255, 255, 255));
        button_return.setText("RETURN");
        button_return.setBorderPainted(false);
        button_return.setContentAreaFilled(false);
        button_return.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_return.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_returnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_returnMouseExited(evt);
            }
        });
        button_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_returnActionPerformed(evt);
            }
        });

        empNumError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        empNumError.setForeground(java.awt.Color.lightGray);
        empNumError.setText("invalid input");

        dRateError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        dRateError.setForeground(java.awt.Color.lightGray);
        dRateError.setText("invalid input");

        hWageError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        hWageError.setForeground(java.awt.Color.lightGray);
        hWageError.setText("invalid input");

        hWeekError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        hWeekError.setForeground(java.awt.Color.lightGray);
        hWeekError.setText("invalid input");

        wYearError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        wYearError.setForeground(java.awt.Color.lightGray);
        wYearError.setText("invalid input");

        fNameError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        fNameError.setForeground(java.awt.Color.lightGray);
        fNameError.setText("please input a name");

        lNameError.setFont(new java.awt.Font("Avenir Next", 2, 13)); // NOI18N
        lNameError.setForeground(java.awt.Color.lightGray);
        lNameError.setText("please input a name");

        sexError.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        sexError.setForeground(java.awt.Color.lightGray);
        sexError.setText("please select one:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(deducRate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstName)
                                    .addComponent(lastName)
                                    .addComponent(empNum, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(hrlyWage, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hrsWeek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(weekYr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(empNumError)
                                            .addComponent(hWageError)
                                            .addComponent(hWeekError))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(button_return)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNameError)
                                    .addComponent(wYearError)
                                    .addComponent(dRateError)
                                    .addComponent(fNameError))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(workLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(male)
                                    .addComponent(female)
                                    .addComponent(other)
                                    .addComponent(button_complete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(sexError)
                                .addGap(109, 109, 109))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNumError)
                    .addComponent(sexError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deducRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4)
                        .addComponent(dRateError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hrlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(1, 1, 1)
                        .addComponent(hWageError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hrsWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(other)
                        .addGap(18, 18, 18)
                        .addComponent(workLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(hWeekError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekYr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_complete, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wYearError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_return)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //if no text resets to light gray and resets to "defaut text"
    //displays error if number given is invalid
    private void empNumfocusL1(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumfocusL1
        if (empNum.getText().equals("")) {
            empNum.setText("Employee Number");
            empNum.setForeground(Color.lightGray);
            empNum.setFont(empNum.getFont().deriveFont(Font.ITALIC));
        }
        try {
            Integer.parseInt(empNum.getText());
        } catch (Exception e) {
            empNumError.setForeground(Color.red);
        }
    }//GEN-LAST:event_empNumfocusL1
    
    private void firstNamefocusL2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNamefocusL2
        // TODO add your handling code here:
        if (firstName.getText().equals("")) {
            firstName.setText("First Name");
            firstName.setForeground(Color.lightGray);
            firstName.setFont(firstName.getFont().deriveFont(Font.ITALIC));
        }
    }//GEN-LAST:event_firstNamefocusL2
    
    private void lastNamefocusL3(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNamefocusL3
        // TODO add your handling code here:
        if (lastName.getText().equals("")) {
            lastName.setText("Last Name");
            lastName.setForeground(Color.lightGray);
            lastName.setFont(lastName.getFont().deriveFont(Font.ITALIC));
        }
    }//GEN-LAST:event_lastNamefocusL3
    
    private void deducRatefocusL4(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deducRatefocusL4
        if (deducRate.getText().equals("")) {
             deducRate.setText("Deduction Rate");
             deducRate.setForeground(Color.lightGray);
             deducRate.setFont(deducRate.getFont().deriveFont(Font.ITALIC));
         }
         try {
             Double.parseDouble(deducRate.getText());
         } catch (Exception e) {
             dRateError.setForeground(Color.red);
         }
     }//GEN-LAST:event_deducRatefocusL4

    private void hrlyWagefosucL5(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hrlyWagefosucL5
        if (hrlyWage.getText().equals("")) {
            hrlyWage.setText("Hourly Wage");
            hrlyWage.setForeground(Color.lightGray);
            hrlyWage.setFont(hrlyWage.getFont().deriveFont(Font.ITALIC));
        }
        try {
            Double.parseDouble(hrlyWage.getText());
        } catch (Exception e) {
            hWageError.setForeground(Color.red);
        }

    }//GEN-LAST:event_hrlyWagefosucL5
    
    //if text is "defaut text" (ex. employee number) sets text to "" and dark gray
    private void hrsWeekfocusL6(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hrsWeekfocusL6
        if (hrsWeek.getText().equals("")) {
            hrsWeek.setText("Hours Per Week");
            hrsWeek.setForeground(Color.lightGray);
            hrsWeek.setFont(hrsWeek.getFont().deriveFont(Font.ITALIC));
        }   
        try {
            Double.parseDouble(hrsWeek.getText());
        } catch (Exception e) {
            hWeekError.setForeground(Color.red);
        }
    }//GEN-LAST:event_hrsWeekfocusL6

    private void weekYrfocusL7(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weekYrfocusL7
        if (weekYr.getText().equals("")) {
            weekYr.setText("Weeks Per Year");
            weekYr.setForeground(Color.lightGray);
            weekYr.setFont(weekYr.getFont().deriveFont(Font.ITALIC));
        }
        try {
            Double.parseDouble(weekYr.getText());
        } catch (Exception e) {
            wYearError.setForeground(Color.red);
        }
    }//GEN-LAST:event_weekYrfocusL7

    private void weekYrfocusG7(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weekYrfocusG7
        // TODO add your handling code here:
        wYearError.setForeground(Color.lightGray);
        if (weekYr.getText().equals("Weeks Per Year")) {
            weekYr.setText("");
            weekYr.setForeground(Color.darkGray);
            weekYr.setFont(weekYr.getFont().deriveFont(Font.PLAIN));
            }
    }//GEN-LAST:event_weekYrfocusG7

    private void hrlyWagefocusG5(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hrlyWagefocusG5
        // TODO add your handling code here:
        hWageError.setForeground(Color.lightGray);
        if (hrlyWage.getText().equals("Hourly Wage")) {
            hrlyWage.setText("");
            hrlyWage.setForeground(Color.darkGray);
            hrlyWage.setFont(hrlyWage.getFont().deriveFont(Font.PLAIN));
            }
    }//GEN-LAST:event_hrlyWagefocusG5

    private void hrsWeekfocusG6(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hrsWeekfocusG6
        // TODO add your handling code here:
        hWeekError.setForeground(Color.lightGray);
        if (hrsWeek.getText().equals("Hours Per Week")) {
            hrsWeek.setText("");
            hrsWeek.setForeground(Color.darkGray);
            hrsWeek.setFont(hrsWeek.getFont().deriveFont(Font.PLAIN));
            }
    }//GEN-LAST:event_hrsWeekfocusG6

    private void deducRatefocusG4(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deducRatefocusG4
        // TODO add your handling code here:
        dRateError.setForeground(Color.lightGray);
        if (deducRate.getText().equals("Deduction Rate")) {
            deducRate.setText("");
            deducRate.setForeground(Color.darkGray);
            deducRate.setFont(deducRate.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_deducRatefocusG4

    private void lastNamefocusG3(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNamefocusG3
        // TODO add your handling code here:
        lNameError.setForeground(Color.lightGray);
        if (lastName.getText().equals("Last Name")) {
            lastName.setText("");
            lastName.setForeground(Color.darkGray);
            lastName.setFont(lastName.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_lastNamefocusG3

    private void firstNamefocusG2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNamefocusG2
        // TODO add your handling code here:
        fNameError.setForeground(Color.lightGray);
        if (firstName.getText().equals("First Name")) {
            firstName.setText("");
            firstName.setForeground(Color.darkGray);
            firstName.setFont(firstName.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_firstNamefocusG2

    //sets text boxes as focusable
    private void empNumfocusG1(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumfocusG1
        // TODO add your handling code here:
        empNumError.setForeground(Color.lightGray);
        if (empNum.getText().equals("Employee Number")) {
            empNum.setText("");
            empNum.setForeground(Color.darkGray);
            empNum.setFont(empNum.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_empNumfocusG1

    private void empNummakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empNummakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_empNummakeFocusable

    private void firstNamemakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNamemakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_firstNamemakeFocusable

    private void lastNamemakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNamemakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_lastNamemakeFocusable

    private void deducRatemakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deducRatemakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_deducRatemakeFocusable

    private void hrlyWagemakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrlyWagemakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_hrlyWagemakeFocusable


    private void hrsWeekmakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrsWeekmakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_hrsWeekmakeFocusable

    private void weekYrmakeFocusable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weekYrmakeFocusable
        // TODO add your handling code here:
        empNum.setFocusable(true);
        firstName.setFocusable(true);
        lastName.setFocusable(true);
        deducRate.setFocusable(true);
        workLocation.setFocusable(true);
        hrlyWage.setFocusable(true);
        hrsWeek.setFocusable(true);
        weekYr.setFocusable(true);
    }//GEN-LAST:event_weekYrmakeFocusable

    //stores selected sex in a variable
    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        sex = 0;
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        sex = 1;
    }//GEN-LAST:event_femaleActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        // TODO add your handling code here:
        sex = 2;
    }//GEN-LAST:event_otherActionPerformed

    //sets foreground to dark gray when mouse is entered
    private void button_returnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnMouseEntered
        // TODO add your handling code here:
        button_return.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_returnMouseEntered

    private void button_completecompleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_completecompleteMouseEntered
        // TODO add your handling code here:
        button_complete.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_completecompleteMouseEntered

    //sets foreground to white when mouse is exited
    private void button_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnMouseExited
        // TODO add your handling code here:
        button_return.setForeground(Color.white);
    }//GEN-LAST:event_button_returnMouseExited

    private void button_completecompleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_completecompleteMouseExited
        // TODO add your handling code here:
        button_complete.setForeground(Color.white);
    }//GEN-LAST:event_button_completecompleteMouseExited

    //exits to main menu if return is pressed
    private void button_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_returnActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_button_returnActionPerformed

    //deletes edited employee and adds new employee with edited information
    private void button_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_completeActionPerformed
        // TODO add your handling code here:
        dRate = Double.parseDouble(deducRate.getText()) / 100;
        MyHashTable hashTable = EmployeeDatabase.returnHashTable();
        int search = hashTable.searchEmployee(employeeNumber);
        int error = 0;
        
        //displays error is one of the inputes is invalid
        if (firstName.getText().equals("First Name")) {
            fNameError.setForeground(Color.red);
            error = 1;
        }
        
        if (lastName.getText().equals("Last Name")) {
            lNameError.setForeground(Color.red);
            error = 1;
        }
        
        if (employeeNumber<0){
            empNumError.setForeground(Color.red);
            error=1;
        }
        
        if (search != -1 && employeeNumber!=originalEmpNum) {
            empNumError.setForeground(Color.red);
            error=1;
        }
        
        if (empNum.getText().equals("Employee Number")) {
            empNumError.setForeground(Color.red);
            error = 1;
        }
        if (deducRate.getText().equals("Deductions Rate")) {
            dRateError.setForeground(Color.red);
            error = 1;
        }
        if (hrlyWage.getText().equals("Hourly Wage")) {
            hWageError.setForeground(Color.red);
            error = 1;
        }
        if (hrsWeek.getText().equals("Hours Per Week")) {
            hWeekError.setForeground(Color.red);
            error = 1;
        }
        if (weekYr.getText().equals("Weeks Per Year")) {
            wYearError.setForeground(Color.red);
            error = 1;
        }
        if (workLoc == -1) {
            workLocation.setForeground(Color.red);
            error = 1;
        }
        if (sex == -1) {
            sexError.setForeground(Color.red);
            error = 1;
        }

        if (error != 1) {
            hashTable.removeEmployee(originalEmpNum);
            //checks if any errors and displays error messages if not adds employee to hashtable

            employeeNumber = Integer.parseInt(empNum.getText());

            fName = firstName.getText();
            lName = lastName.getText();

            if (workLocation.getSelectedItem() == "Toronto") {
                workLoc = 0;
            } else if (workLocation.getSelectedItem() == "Mississauga") {
                workLoc = 1;
            } else if (workLocation.getSelectedItem() == "Ottawa") {
                workLoc = 2;
            } else {
                workLoc = -1;
            }
            hrWage = Double.parseDouble(hrlyWage.getText());
            hrWeek = Double.parseDouble(hrsWeek.getText());
            wkYear = Double.parseDouble(weekYr.getText());

            employee = new PartTimeEmployee(employeeNumber, fName, lName, sex, workLoc, dRate, hrWage, hrWeek, wkYear);


            hashTable.addEmployee(employee);

            dispose();
            new MainMenu().setVisible(true);
            new EditSuccessfulFrame().setVisible(true);
        
        }
    }//GEN-LAST:event_button_completeActionPerformed

    //returns variable value to display in textbox
    private String getEmpNum() {
        return Integer.toString(employeeNumber);
    }

    private String getFirstName() {
        return fName;
    }

    private String getLastName() {
        return lName;
    }

    private String getDRate() {
        return Double.toString(dRate);
    }

    private String getHrWage() {
        if (hrWage == -1){
            hrlyWage.setText("Hourly Wage");
            hrlyWage.setForeground(Color.lightGray);
            hrlyWage.setFont(hrlyWage.getFont().deriveFont(Font.ITALIC));
            return ("Hourly Wage");
        }
        else {
            return Double.toString(hrWage);
        }
    }

    //if not variable value displays "default text"
    private String getHrWeek() {
        if (hrWeek == -1){
            hrsWeek.setText("Hours Per Week");
            hrsWeek.setForeground(Color.lightGray);
            hrsWeek.setFont(hrsWeek.getFont().deriveFont(Font.ITALIC));
            return ("Hours Per Week");
        }
        else {
            return Double.toString(hrWeek);
        }
    }

    private String getWkYear() {
        if (wkYear == -1){
            weekYr.setText("Weeks Per Year");
            weekYr.setForeground(Color.lightGray);
            weekYr.setFont(weekYr.getFont().deriveFont(Font.ITALIC));
            return ("Weeks Per Year");
        }
        else {
            return Double.toString(wkYear);
        }
    }
    
    private boolean getSexMale() {
        if (sex == 0){
            return (true);
        }
        else{
            return (false);
        }
    }
    private boolean getSexFemale() {
        if (sex == 1){
            return (true);
        }
        else{
            return (false);
        }
    }
    private boolean getSexOther() {
        if (sex == 2){
            return (true);
        }
        else{
            return (false);
        }
    }
    private int getWorkLoc(){
        return (workLoc+1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPartTimeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPartTimeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPartTimeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPartTimeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPartTimeEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_complete;
    private javax.swing.JButton button_return;
    private javax.swing.JLabel dRateError;
    private javax.swing.JTextField deducRate;
    private javax.swing.JTextField empNum;
    private javax.swing.JLabel empNumError;
    private javax.swing.JLabel fNameError;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel hWageError;
    private javax.swing.JLabel hWeekError;
    private javax.swing.JTextField hrlyWage;
    private javax.swing.JTextField hrsWeek;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNameError;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton other;
    private javax.swing.JLabel sexError;
    private javax.swing.JLabel wYearError;
    private javax.swing.JTextField weekYr;
    private javax.swing.JComboBox<String> workLocation;
    // End of variables declaration//GEN-END:variables
}
