/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Megan
 */
public class EditEmployeeSearchFrame extends javax.swing.JFrame {

    private static int numInList;
    static int empNum;

    /**
     * Creates new form EditEmployeeSearchFrame
     */
    public EditEmployeeSearchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        button_search = new javax.swing.JButton();
        empNumber = new javax.swing.JTextField();
        button_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(461, 178));

        title.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 102));
        title.setText("SEARCH FOR EMPLOYEE");

        button_search.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("SEARCH");
        button_search.setBorderPainted(false);
        button_search.setContentAreaFilled(false);
        button_search.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_search.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_searchsearchMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_searchsearchMouseEntered(evt);
            }
        });
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        empNumber.setFont(new java.awt.Font("Avenir Next", 2, 18)); // NOI18N
        empNumber.setForeground(java.awt.Color.lightGray);
        empNumber.setText("Employee Number");
        empNumber.setFocusable(false);
        empNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empNumberFocusLost(evt);
            }
        });
        empNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empNumberMouseEntered(evt);
            }
        });

        button_return.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_return.setForeground(new java.awt.Color(255, 255, 255));
        button_return.setText("RETURN");
        button_return.setBorderPainted(false);
        button_return.setContentAreaFilled(false);
        button_return.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_return.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_returnreturnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_returnreturnMouseEntered(evt);
            }
        });
        button_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(button_return, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_return, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_searchsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_searchsearchMouseExited
        // TODO add your handling code here:
        button_search.setForeground(Color.white);
    }//GEN-LAST:event_button_searchsearchMouseExited

    private void button_searchsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_searchsearchMouseEntered
        // TODO add your handling code here:
        button_search.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_searchsearchMouseEntered

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:

        MyHashTable hashTable = EmployeeDatabase.returnHashTable();
        //finds the searched employee's number in list
        numInList = hashTable.searchEmployee(Integer.parseInt(empNumber.getText()));
        //stores employee number as an integer
        empNum = Integer.parseInt(empNumber.getText());

        dispose();
        //shows an error if the employee number is not in the  database, opens window to chose employee type if is
        if (hashTable.searchEmployee(empNum) == -1) {
            new ErrorEditFrame().setVisible(true);
        } else {
            new EditEmployeeChangeType().setVisible(true);
        }
    }//GEN-LAST:event_button_searchActionPerformed
    //erases text "employee number" when focus is gained
    private void empNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumberFocusGained
        // TODO add your handling code here:
        if (empNumber.getText().equals("Employee Number")) {
            empNumber.setText("");
            empNumber.setForeground(Color.darkGray);
            empNumber.setFont(empNumber.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_empNumberFocusGained
    //when focus is lost if no text is written, resets text to light gray and italic and to employee number
    private void empNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumberFocusLost
        // TODO add your handling code here:
        if (empNumber.getText().equals("")) {
            empNumber.setText("Employee Number");
            empNumber.setForeground(Color.lightGray);
            empNumber.setFont(empNumber.getFont().deriveFont(Font.ITALIC));
        }
    }//GEN-LAST:event_empNumberFocusLost

    private void empNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empNumberMouseEntered
        // TODO add your handling code here:
        empNumber.setFocusable(true);
    }//GEN-LAST:event_empNumberMouseEntered
    //changes foreground color to white when the mouse is exited
    private void button_returnreturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnreturnMouseExited
        // TODO add your handling code here:
        button_return.setForeground(Color.white);
    }//GEN-LAST:event_button_returnreturnMouseExited
    //changes foreground color to dark gray when mouse is exited
    private void button_returnreturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnreturnMouseEntered
        // TODO add your handling code here:
        button_return.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_returnreturnMouseEntered
    //exits to the main menu when return is pressed
    private void button_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_returnActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_button_returnActionPerformed

    //returns the employee's position in the hash bucket
    public static int returnSearch() {
        return numInList;
    }

    public static int getEmpNum() {
        return empNum;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_return;
    private javax.swing.JButton button_search;
    private javax.swing.JTextField empNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    static class returnSearch {

        public int returnSearch() {
            return numInList;
        }
    }
}
