/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import java.awt.Color;
import java.io.PrintWriter;

/**
 *
 * @author Patricia
 */
public class ExitCheckFrame extends javax.swing.JFrame {
    private int sex;
    private int employeeNumber;
    private String fName;
    private String lName;
    private int workLoc;
    private double dRate;
    private double yrIncome;
    private double salary;
    private double hrWage;
    private double hrWeek;
    private double wkYear;

    /**
     * Creates new form ExitCheckFrame
     */
    public ExitCheckFrame() {
        initComponents();
    }  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_no = new javax.swing.JButton();
        button_yes = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        button_no.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        button_no.setForeground(new java.awt.Color(255, 255, 255));
        button_no.setText("NO");
        button_no.setBorderPainted(false);
        button_no.setContentAreaFilled(false);
        button_no.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_no.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_noremoveMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_noremoveMouseEntered(evt);
            }
        });
        button_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_noActionPerformed(evt);
            }
        });

        button_yes.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        button_yes.setForeground(new java.awt.Color(255, 255, 255));
        button_yes.setText("YES");
        button_yes.setBorderPainted(false);
        button_yes.setContentAreaFilled(false);
        button_yes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_yes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_yesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_yesMouseEntered(evt);
            }
        });
        button_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_yesActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Would you like to exit?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_no)
                .addGap(93, 93, 93)
                .addComponent(button_yes)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_yes)
                    .addComponent(button_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_noremoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_noremoveMouseExited
        // TODO add your handling code here:
        button_no.setForeground(Color.white);
    }//GEN-LAST:event_button_noremoveMouseExited

    private void button_noremoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_noremoveMouseEntered
        // TODO add your handling code here:
        button_no.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_noremoveMouseEntered

    private void button_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_noActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button_noActionPerformed

    private void button_yesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_yesMouseExited
        // TODO add your handling code here:
        button_yes.setForeground(Color.white);
    }//GEN-LAST:event_button_yesMouseExited

    private void button_yesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_yesMouseEntered
        // TODO add your handling code here:
        button_yes.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_yesMouseEntered

    private void button_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_yesActionPerformed
        // TODO add your handling code here:
        try {
            PrintWriter writer = new PrintWriter("EmployeeDatabaseArchive.txt", "UTF-8");

            for (int x = 0; x < MyHashTable.numOfBuckets(); x++) {

                for (int y = 0; y < MyHashTable.buckets[x].size(); y++) {

                    EmployeeInfo employee = MyHashTable.buckets[x].get(y);

                    employeeNumber = employee.getEmpNumber();
                    fName = employee.getFirstName();
                    lName = employee.getLastName();
                    yrIncome = employee.calcAnnualIncome();
                    dRate = employee.getDedustionsRate() * 100;
                    sex = employee.getSex();
                    workLoc = employee.getWorkLocation();

                    if (employee.empType().equals("f")) {

                        salary = employee.getAnnualIncome();

                        writer.println("f@" + employeeNumber + "@" + fName + "@" + lName + "@" + dRate + "@" + sex + "@" + workLoc + "@" + salary + "@" + yrIncome);

                    } else if (employee.empType().equals("p")) {
                        hrWage = employee.getHourlyWage();
                        hrWeek = employee.getHoursPerWeek();
                        wkYear = employee.getWeeksPerYear();

                        writer.println("p@" + employeeNumber + "@" + fName + "@" + lName + "@" + dRate + "@" + sex + "@" + workLoc + "@" + hrWage + "@" + hrWeek + "@" + wkYear + "@" + yrIncome);
                    }
                }

            }

            writer.close();
        } catch (Exception e) {
            // do something
        }
        System.exit(0);
    }//GEN-LAST:event_button_yesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitCheckFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitCheckFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitCheckFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitCheckFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitCheckFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_no;
    private javax.swing.JButton button_yes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
