package employeedatabase;

import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Patricia
 */
public class RemoveEmployeeFrame extends javax.swing.JFrame {

    private static int empNum = -1;

    /**
     * Creates new form RemoveEmployeeFrame
     */
    public RemoveEmployeeFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empNumber = new javax.swing.JTextField();
        button_remove = new javax.swing.JButton();
        button_return = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("REMOVE EMPLOYEE");

        empNumber.setFont(new java.awt.Font("Avenir Next", 2, 18)); // NOI18N
        empNumber.setForeground(java.awt.Color.lightGray);
        empNumber.setText("Employee Number");
        empNumber.setActionCommand("<Not Set>");
        empNumber.setFocusable(false);
        empNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empNumberFocusLost(evt);
            }
        });
        empNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empNumberMouseEntered(evt);
            }
        });

        button_remove.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_remove.setForeground(new java.awt.Color(255, 255, 255));
        button_remove.setText("REMOVE");
        button_remove.setBorderPainted(false);
        button_remove.setContentAreaFilled(false);
        button_remove.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_remove.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeMouseEntered(evt);
            }
        });
        button_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_removeActionPerformed(evt);
            }
        });

        button_return.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_return.setForeground(new java.awt.Color(255, 255, 255));
        button_return.setText("RETURN");
        button_return.setBorderPainted(false);
        button_return.setContentAreaFilled(false);
        button_return.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_return.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_returnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_returnMouseEntered(evt);
            }
        });
        button_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(button_return)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_remove)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_return))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseExited
        // TODO add your handling code here:
        button_remove.setForeground(Color.white);
    }//GEN-LAST:event_removeMouseExited

    private void removeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseEntered
        // TODO add your handling code here:
        button_remove.setForeground(Color.darkGray);
    }//GEN-LAST:event_removeMouseEntered

    private void button_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_removeActionPerformed
        // TODO add your handling code here:
        MyHashTable hashTable = EmployeeDatabase.returnHashTable();
        
        if (hashTable.searchEmployee(Integer.parseInt(empNumber.getText())) == -1) {
            dispose();
            new ErrorRemoveFrame().setVisible(true);
        } else {
            empNum = Integer.parseInt(empNumber.getText());

            dispose();
            new CheckRemoveFrame().setVisible(true);
        }

    }//GEN-LAST:event_button_removeActionPerformed

    private void empNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumberFocusGained
        // TODO add your handling code here:
        if (empNumber.getText().equals("Employee Number")) {
            empNumber.setText("");
            empNumber.setForeground(Color.darkGray);
            empNumber.setFont(empNumber.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_empNumberFocusGained

    private void empNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empNumberFocusLost
        // TODO add your handling code here:
        if (empNumber.getText().equals("")) {
            empNumber.setText("Employee Number");
            empNumber.setForeground(Color.lightGray);
            empNumber.setFont(empNumber.getFont().deriveFont(Font.ITALIC));
        }
    }//GEN-LAST:event_empNumberFocusLost

    private void empNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empNumberMouseEntered
        // TODO add your handling code here:
        empNumber.setFocusable(true);
    }//GEN-LAST:event_empNumberMouseEntered

    private void button_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_returnActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_button_returnActionPerformed

    private void button_returnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnMouseEntered
        // TODO add your handling code here:
        button_return.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_returnMouseEntered

    private void button_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_returnMouseExited
        // TODO add your handling code here:
        button_return.setForeground(Color.white);
    }//GEN-LAST:event_button_returnMouseExited

    public static int empToRemove() {
        return empNum;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_remove;
    private javax.swing.JButton button_return;
    private javax.swing.JTextField empNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
