/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import static employeedatabase.MyHashTable.buckets;
import java.awt.Color;

/**
 *
 * @author Patricia
 */
public class SearchReturn extends javax.swing.JFrame {

    private String sex;
    private String workLoc;

    /**
     * Creates new form SearchReturn
     */
    public SearchReturn() {
        initComponents();

        if (SearchEmployeeFrame.returnSearch() == -1) {
            empInfo.setForeground(Color.red);
            empInfo.append("this employee does not exist");
        } else {

            empInfo.append("\n Employee Number: " + SearchEmployeeFrame.getEmpNum());

            MyHashTable hashTable = EmployeeDatabase.returnHashTable();

            int bucketNum = hashTable.calcBucket(SearchEmployeeFrame.getEmpNum());

            for (int x = 0; x < buckets[bucketNum].size(); x++) {

                EmployeeInfo employee = buckets[bucketNum].get(x);

                if (employee.getSex() == 0) {
                    sex = "male";
                } else if (employee.getSex() == 1) {
                    sex = "female";
                } else if (employee.getSex() == 2) {
                    sex = "other";
                }

                if (employee.getWorkLocation() == 0) {
                    workLoc = "Toronto";
                } else if (employee.getWorkLocation() == 1) {
                    workLoc = "Mississauga";
                } else if (employee.getWorkLocation() == 2) {
                    workLoc = "Ottawa";
                }

                if (employee.getEmpNumber() == SearchEmployeeFrame.getEmpNum()) {
                    empInfo.append("\n First Name: " + employee.getFirstName());
                    empInfo.append("\n Last Name: " + employee.getLastName());
                    empInfo.append("\n Sex: " + sex);
                    empInfo.append("\n Work Location: " + workLoc);
                    empInfo.append("\n Deductions Rate: " + employee.getDedustionsRate() * 100 + "%");

                    if (employee.empType().equals("p")) {
                        double hrWage = employee.getHourlyWage();
                        double hrWeek = employee.getHoursPerWeek();
                        double wkYear = employee.getWeeksPerYear();
                        empInfo.append("\n Hourly Wage: " + hrWage);
                        empInfo.append("\n Hours Per Week: " + hrWeek);
                        empInfo.append("\n Weeks Per Year: " + wkYear);
                    } else if (employee.empType().equals("f")) {
                        double salary = employee.getAnnualIncome();
                        empInfo.append("\n Yearly Salary: " + salary);
                    }

                    empInfo.append("\n Annual Income: " + employee.calcAnnualIncome());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        empInfo = new javax.swing.JTextArea();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        title.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        title.setForeground(java.awt.Color.darkGray);
        title.setText("Employee Searched:");

        empInfo.setEditable(false);
        empInfo.setBackground(new java.awt.Color(204, 204, 204));
        empInfo.setColumns(20);
        empInfo.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        empInfo.setForeground(java.awt.Color.darkGray);
        empInfo.setRows(5);

        button_back.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        button_back.setForeground(new java.awt.Color(255, 255, 255));
        button_back.setText("BACK TO MENU");
        button_back.setBorderPainted(false);
        button_back.setContentAreaFilled(false);
        button_back.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        button_back.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        button_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_backbackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_backbackMouseEntered(evt);
            }
        });
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_back)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(empInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(empInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_backbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_backbackMouseExited
        // TODO add your handling code here:
        button_back.setForeground(Color.white);
    }//GEN-LAST:event_button_backbackMouseExited

    private void button_backbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_backbackMouseEntered
        // TODO add your handling code here:
        button_back.setForeground(Color.darkGray);
    }//GEN-LAST:event_button_backbackMouseEntered

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_button_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back;
    private javax.swing.JTextArea empInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
