package employeedatabase;


import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patricia
 */
public class SelectEmpType extends javax.swing.JFrame {

    /**
     * Creates new form SelectEmpType
     */
    public SelectEmpType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectTypePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        button_partTime = new javax.swing.JButton();
        button_fullTime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        selectTypePanel.setBackground(new java.awt.Color(204, 204, 204));

        titleLabel.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 102, 102));
        titleLabel.setText("SELECT EMPLOYEE TYPE");

        button_partTime.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        button_partTime.setForeground(java.awt.Color.darkGray);
        button_partTime.setText("Part Time");
        button_partTime.setBorderPainted(false);
        button_partTime.setContentAreaFilled(false);
        button_partTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitedB1(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredB1(evt);
            }
        });
        button_partTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_partTimeActionPerformed(evt);
            }
        });

        button_fullTime.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        button_fullTime.setForeground(java.awt.Color.darkGray);
        button_fullTime.setText("Full Time");
        button_fullTime.setBorderPainted(false);
        button_fullTime.setContentAreaFilled(false);
        button_fullTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitedB2(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredB2(evt);
            }
        });
        button_fullTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fullTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectTypePanelLayout = new javax.swing.GroupLayout(selectTypePanel);
        selectTypePanel.setLayout(selectTypePanelLayout);
        selectTypePanelLayout.setHorizontalGroup(
            selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectTypePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(button_partTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_fullTime)
                .addGap(43, 43, 43))
            .addGroup(selectTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        selectTypePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_fullTime, button_partTime});

        selectTypePanelLayout.setVerticalGroup(
            selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_partTime)
                    .addComponent(button_fullTime))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        selectTypePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_fullTime, button_partTime});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_partTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_partTimeActionPerformed
        dispose(); 
        
        //opens the add part time employee frame
        new AddEmployeePartTimeFrame().setVisible(true);
    }//GEN-LAST:event_button_partTimeActionPerformed

    private void button_fullTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fullTimeActionPerformed
        dispose();
        
        //opens the add full time employee frame
        new AddEmployeeFullTimeFrame().setVisible(true);
    }//GEN-LAST:event_button_fullTimeActionPerformed

    //changes text colour of each button to white upon mouse enterance
    private void mouseEnteredB1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredB1
        button_partTime.setForeground(Color.white);
    }//GEN-LAST:event_mouseEnteredB1
    
    private void mouseEnteredB2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredB2
        button_fullTime.setForeground(Color.white);
    }//GEN-LAST:event_mouseEnteredB2

    //changes text colour of each button to dark gray upon mouse exit
    private void mouseExitedB1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitedB1
        button_partTime.setForeground(Color.darkGray);
    }//GEN-LAST:event_mouseExitedB1

    private void mouseExitedB2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitedB2
        button_fullTime.setForeground(Color.darkGray);
    }//GEN-LAST:event_mouseExitedB2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectEmpType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectEmpType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectEmpType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectEmpType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectEmpType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_fullTime;
    private javax.swing.JButton button_partTime;
    private javax.swing.JPanel selectTypePanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
